import tabNav from "./scripts/tabNav.js";
import scrollSuave from "./scripts/scrollSUave.js";
import faqClick from "./scripts/faqClick.js";
import scrollAnimacao from "./scripts/scrollAnimacao.js";
import modal from "./scripts/modal.js";
import menuMobile from "./scripts/menuMobile.js";
import toolTip from "./scripts/tooltip.js";
import dropDownMenu from "./scripts/dropdown.js";
import initNum from "./scripts/numeros.js";
import funcionamento from "./scripts/funcionamento.js";
import Bitcoin from "./scripts/fetcBtc.js";

tabNav();
scrollSuave();
faqClick();
scrollAnimacao();
modal();
menuMobile();
toolTip();
dropDownMenu();
initNum();
funcionamento();
Bitcoin();
