import scrollAnimacao from "./scripts/scrollAnimacao.js";
import modal from "./scripts/modal.js";
import menuMobile from "./scripts/menuMobile.js";
import toolTip from "./scripts/tooltip.js";
import dropDownMenu from "./scripts/dropdown.js";
import initNum from "./scripts/numeros.js";
import funcionamento from "./scripts/funcionamento.js";
import Bitcoin from "./scripts/fetcBtc.js";
import navegacaoPorTab from "./scripts/tabNav.js";
import scrollClick from "./scripts/scrollClick.js";
import faqClick from "./scripts/faqClick.js";
faqClick();
navegacaoPorTab();
scrollClick();
funcionamento();
Bitcoin();
initNum();
dropDownMenu();
toolTip();
menuMobile();
modal();
scrollAnimacao();
